# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
###########################################################
# Step 1: Retrieve the cached .m2 directory from GCS
###########################################################
- name: gcr.io/cloud-builders/gsutil
  id: fetch-mvn-cache
  args:
    - '-m'
    - 'rsync'
    - '-r'
    - 'gs://${_BUCKET}/cache/.m2'
    - '/cache/.m2'
  volumes:
    - path: '/cache/.m2'
      name: 'm2_cache'

###########################################################
# Step 2: Run project integration tests using Maven
###########################################################
- name: gcr.io/cloud-devrel-public-resources/java11
  id: pr-integration-tests
  waitFor:
    - fetch-mvn-cache
  entrypoint: bash
  args:
    - "-e"
    - "./ci/integration.sh"
  volumes:
    - path: '/cache/.m2'
      name: 'm2_cache'
  env:
    - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
    - PROJECT=enpa-integration-testing
    - KEY_RESOURCE_NAME=projects/enpa-integration-testing/locations/global/keyRings/appa-signature-key/cryptoKeys/appa-signature-key/cryptoKeyVersions/1

###########################################################
# Step 3: Run Firebase integration tests using npm
########################################################### 
- name: gcr.io/enpa-public-assets/firestore-tesing:v1
  id: firebase-integration-tests
  waitFor: 
    - '-'
  entrypoint: bash
  args:
    - "-e"
    - "./ci/firebase.sh"
  env:
    - PROJECT=enpa-integration-testing

###########################################################
# Step 4: Update cached .m2 directory on GCS with any
#         additional dependencies downloaded during the
#         build.
###########################################################
- name: gcr.io/cloud-builders/gsutil
  id: sync-mvn-cache
  waitFor:
    - pr-integration-tests
  args:
    - '-m'
    - 'rsync'
    - '-r'
    - '/cache/.m2'
    - 'gs://${_BUCKET}/cache/.m2/'
  volumes:
    - path: '/cache/.m2'
      name: 'm2_cache'

serviceAccount: 'projects/enpa-infra/serviceAccounts/development-integration-tests@enpa-integration-testing.iam.gserviceaccount.com'

substitutions:
  # Default value
  _BUCKET: 'enpa-infra'

options:
  # Use higher CPU machines so the caching and build steps are faster.
  machineType: 'N1_HIGHCPU_32'